name = "test function"
version = "1.0.0"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "test function_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "test function.wasm"
command = "npm run build:release"
